// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6JlRWNiiy9gnzWJQX7fkFz2qyyxLtcM0',
    appId: '1:169753240575:web:3077bff156280fb336bdca',
    messagingSenderId: '169753240575',
    projectId: 'ci-cd-35204',
    authDomain: 'ci-cd-35204.firebaseapp.com',
    storageBucket: 'ci-cd-35204.appspot.com',
    measurementId: 'G-V8NS4PPCS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjPMpjkNB8IvGmngknsMMS-TRcP-ycv-w',
    appId: '1:169753240575:android:3213488e74be00e836bdca',
    messagingSenderId: '169753240575',
    projectId: 'ci-cd-35204',
    storageBucket: 'ci-cd-35204.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2sI3T4d03Ud5iGypM27bEhTGS26WLZUE',
    appId: '1:169753240575:ios:ef2dee5687b1c50236bdca',
    messagingSenderId: '169753240575',
    projectId: 'ci-cd-35204',
    storageBucket: 'ci-cd-35204.appspot.com',
    iosClientId: '169753240575-9fdna7udhe5d7uiko6fu9p674en1f9i6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ciCd1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2sI3T4d03Ud5iGypM27bEhTGS26WLZUE',
    appId: '1:169753240575:ios:ef2dee5687b1c50236bdca',
    messagingSenderId: '169753240575',
    projectId: 'ci-cd-35204',
    storageBucket: 'ci-cd-35204.appspot.com',
    iosClientId: '169753240575-9fdna7udhe5d7uiko6fu9p674en1f9i6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ciCd1',
  );
}
